# [Tentative Title] Population Dynamics of the Plant Pathogen *Phytophthora syringae* in Oregon Nurseries

## Abstract

## Introduction

<!-- ZHIAN

please note, This will not be the final draft. I took this from my project
proposal and plan to rework it.

 -->

*Phytophthora syringae* is the most important species affecting ornamentals
produced in the Pacific Northwest. Recent nursery sampling efforts, aimed at
characterizing the diversity of *Phytophthoras* within Oregon nurseries, have
revealed the species *P. syringae* to be among the most abundant taxa found in
the nurseries surveyed [@parke2014phytophthora]. *P. syringae* is adapted to
cold weather and grows best in the cool, wet fall, winter and spring and is
least active in summer [@erwin1996phytophthora]. Like *P. ramorum*, it has a
wide host range including *Rhododendron*, *Camellia*, *Malus*, and many other
taxa. It has the capability for outcrossing, self-fertilizing, and reproducing
clonally. This pathogen has been found globally since 1881 and is problematic on
woody ornamentals such as crabapple (*Malus spp.*), as it causes unsightly
cankers that make the plant unsellable [@erwin1996phytophthora]. While the
ecology of this pathogen has been studied to some degree, very little is known
about the demographic history and population structure on a local and global
scale.