The following people contributed to this dissertation: 
<!-- Note: you MUST have a line at the beginning of all pretext pages -->



#### Chapter 2 {-}


Zhian N. Kamvar conceived and designed the experiments, performed the
experiments, analyzed the data, contributed reagents/materials/analysis tools,
wrote the paper, prepared figures and/or tables, reviewed drafts of the paper.

Javier F. Tabima conceived and designed the experiments, performed the
experiments, analyzed the data, contributed reagents/materials/analysis tools,
prepared figures and/or tables, reviewed drafts of the paper.

Niklaus J. Grünwald conceived and designed the experiments, analyzed the data,
contributed reagents/materials/analysis tools, wrote the paper, reviewed drafts
of the paper.


#### Chapter 3 {-}


Zhian N. Kamvar and Jonah C. Brooks wrote and tested the code. Zhian N. Kamvar
and Niklaus J. Grünwald conceived, discussed implications, and wrote the
manuscript. Niklaus J. Grünwald coördinated the collaborative effort.


#### Chapter 4 {-}


Zhian N. Kamvar designed and ran the computational analyses, interpreted the
results, and wrote the manuscript Meredeth M. Larsen extracted DNA and genotyped
isolates of *P. ramorum* from 2013 and 2014 at 14 microsatellite loci,
harmonized the data between labs and wrote the genotyping methods. Alan M.
Kanaskie collected *P. ramorum* isolates from infected plant material, performed
field surveys, GIS work, and geotagging with the Brooking SOD ground crew and
assisted with writing of the manuscript, Everett M. Hansen provided data,
strains were isolated by Paul Reeser and Wendy Sutton, and genotyped by Jen
Britt. Everett M. Hansen assisted with writing the manuscript, and Niklaus J.
Grünwald conceived the study, analyzed the data, contributed
reagents/materials/analysis tools, and wrote the paper.


#### Chapter 5 {-}


Zhian N. Kamvar designed the simulations and analyses, analyzed the data, 
interpreted the data, and wrote the manuscript. Niklaus J. Grünwald conceived
the study and reviewed drafts of the manuscript.
